#!/bin/sh

set -e

# Trigger an update to let our new udev rules be immediately effective without
# requiring a system reboot.
# Usually `--reload-rules` is unnecessary, but it doesn't do any harm.
udevadm control --reload-rules || true
udevadm trigger --action=change --sysname-match=uinput || true
udevadm trigger --action=change --subsystem-match=usb --attr-match=idVendor=28de || true
udevadm trigger --action=change --subsystem-match=hidraw || true

#DEBHELPER#
