com.valvesoftware.Steam.metainfo.xml usr/share/metainfo

debian/scripts/steam usr/games
debian/steam.desktop usr/share/applications

debian/icons/16/steam.png usr/share/icons/hicolor/16x16/apps
debian/icons/24/steam.png usr/share/icons/hicolor/24x24/apps
debian/icons/32/steam.png usr/share/icons/hicolor/32x32/apps
debian/icons/48/steam.png usr/share/icons/hicolor/48x48/apps
debian/icons/256/steam.png usr/share/icons/hicolor/256x256/apps
