#!/bin/sh
set -e

. /usr/share/debconf/confmodule

# Nvidia driver detection borrowed from Flatpak
need_nvidia="$(if test -e /sys/module/nvidia/version; then echo yes; fi)"

nvidia_i386="$(dpkg-query -W -f '${Status}' nvidia-driver-libs:i386 2>/dev/null || true)"

if [ -n "$need_nvidia" ] && [ "$nvidia_i386" != 'install ok installed' ]; then
    db_input high steam/need-nvidia-i386 || true
    db_go
fi

#DEBHELPER#
